### ISSUE TITLE
Not valid Assoc beans generated, when more entityBeanPackage provided in generator

### ISSUE THREAD

**Issue by vilmosnagy** [ebean-orm/avaje-ebeanorm-typequery-generator#8]
Hi!

If I'm right I can provide more package to the generator, as the the entity beans' package, because the `MetaReader` will split them by `,`

In that case wrong QAssocBeans will be generated, 'casue the `import` statement will contain each package, in one line.

For example:

    import org.example.domain,org.example.enums.Address;

For a full example, see: https://github.com/vilmosnagy/avaje-ebeanorm-examples/tree/bugs/typequery_more_package/a-basic

**Comment by rbygrave** [comment]
Note: I reviewed the code after the merge and noted that the code was removing and then adding the entity bean class to the imports (which it really didn't need to do).  So the later commit actually removed those lines of code.  The net result is the same, fixing the import of the entity bean class on associated beans when the package is a comma delimited list.

So I am happy with this fix.
